# Generated by Django 3.0.7 on 2020-06-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200604_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='BlogEntry',
            new_name='Entry',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='blogpost',
            new_name='blog',
        ),
    ]
