# Generated by Django 3.0.7 on 2020-06-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
